duckduckgo/ddg2dnr

- lib/extensionConfiguration.js
- lib/trackerAllowlist.js
- lib/trackerBlocking.js
- package-lock.json
- package.json
- puppeteerInterface.js
- test/extensionConfiguration.js
- test/trackerBlocking.js
- tsconfig.json
While we're not switching to TypeScript, we can still make use of
TypeScript linting with JSDoc comments. That should help reduce typos
and similar bugs from sneaking into the codebase.
Note: In the future it would be nice to enable TypeScript linting for
puppeteerInterface.js and enable the "noImplicitAny" option.
> Enable TypeScript linting

- .github/dependabot.yml
Dependabot[1] is a service that can warn developers about outdated and
insecure dependencies. Let's enable that here.
1 - https://docs.github.com/en/code-security/dependabot
> Set up Dependabot insecure dependency alerts

- lib/trackerAllowlist.js
- lib/trackerBlocking.js
- package-lock.json
- package.json
- tsconfig.json
Add JSDoc comment for getTrackerEntryDomain, since Jonathan asked for
that. Also, take care to import the proper type definitions for
tracker blocking rules from the privacy-grade repository rather than
just using the Object type for those. In the future we can make use of
those type definitions elsewhere too.
> Add JSDoc comment for getTrackerEntryDomain

- lib/extensionConfiguration.js
- lib/tds.js
- lib/trackerAllowlist.js
- lib/utils.js
- test/tds.js
The declarativeNetRequest rule generation and "tracker rule" parsing
logic are not unique to TDS. Let's move it all out from tds.js into
the shared utils.js module.
>  Move some shared Tracker Blocking logic into utils

- README.md
Let's add the "-input" and "-output" suffix to filenames in the
README's example commands, so that it's more obvious which files the
commands read from and write to.
> Make example commands in README easier to understand

- README.md
- cli.js
- lib/tds.js
- test/referenceTests.js
- test/tds.js
The DuckDuckGo Privacy Essentials browser extension has "surrogate
scripts" which are stubbed out placeholders for commonly found
third-party scripts. By redirecting requests to those scripts, instead
of blocking them outright, some website breakage can be avoided. Those
scripts often provide an API on window that websites then assume will
always be present. When those APIs aren't found, some websites will
fail to work correctly.  Let's add support for generating the
necessary redirection rules for those scripts.
Note:
- Such redirections sometimes fail in Chrome currently with an
"net::ERR_UNSAFE_REDIRECT" error. See https://crbug.com/1361350.
>  Add support for "surrogate script" redirection rules

- .github/workflows/tests.yml
For some reason, the test are failing intermittently when run by GitHub's macOS test runner. Let's disable the macOS runner for now, we can re-enable it again when we (or GitHub) get to the bottom of the problem.
> Disable macos-latest GitHub runner for now

- lib/rulePriorities.js
- test/rulePriorities.js
Some declarativeNetRequest rules that the DuckDuckGo extension generates do not relate directly to an extension
configuration (e.g. the block list), but rather to the extension's state (e.g. the user clicked to allowlist a website). Let's add a place to put the priorities for those rules, so that the relative priorities for all declarativeNetRequest rules can be properly tested.
> Specify the priority for extension-state based rules

- lib/tds.js
- test/tds.js
Tracker entries always need a default action of either 'ignore' (becoming 'allow' for declarativeNetRequest) or 'block'.
Tracker rules have the default action of 'block', but still for now must have an action of either 'ignore' or 'block. In the future, there will be more supported actions for tracker rules, for example special actions for the "Click to Load" feature.
Take care to drop tracker rules and entries that have unknown actions. That way the block list can be updated, without unsupported rule actions from resulting in incorrect request block/allow outcomes.
> Ignore tracker entries and rules with unknown actions

- cli.js
- lib/extensionConfiguration.js
- lib/temporaryAllowlist.js
- lib/trackerAllowlist.js
- test/extensionConfiguration.js
- test/rulePriorities.js
- test/temporaryAllowlist.js
- test/trackerAllowlist.js
Add contentBlocking, unprotectedTemporary and denylisting support
The extension configuration (extension-config.json) has several
different ways for privacy protections to be disabled for a
website. Important for when a website is broken by our protections. We
need to support those for Chrome MV3. So far, we support the
trackerAllowlist[1], but not the contentBlocking[2] or
unprotectedTemporary[3] allowlists.
Furthermore, the user is allowed to override the contentBlocking and
unprotectedTemporary allowlists by "denylisting" a website. We need to
add Chrome MV3 support for that too.
1 - https://github.com/duckduckgo/privacy-configuration/blob/main/features/tracker-allowlist.json
2 - https://github.com/duckduckgo/privacy-configuration/blob/main/features/content-blocking.json
3 - …
> Add contentBlocking, unprotectedTemporary and denylisting support

- lib/utils.js
The generateDNRRule rule was originally just for generating the
declarativeNetRequest rules necessary for Tracker Blocking. As we
expand to include more privacy features, more rule actions and
conditions need to be supported. Jason is working on adding GPC[1]
protection now, but for that he needs to omit the requestDomains
condition and to specify header modifying actions.
1 - https://help.duckduckgo.com/duckduckgo-help-pages/privacy/gpc/
> Expand generateDNRRule for GPC protection rules

- lib/rulePriorities.js
- test/rulePriorities.js
We do not block ServiceWorker initiated requests yet, as doing so led
to major website breakage in the past. We're going to implement that
for Chrome MV3 with an allowing rule that matches tabs with an ID of
-1. For that, we will need a rule priority that is higher than the
blocking/redirecting rules of our protections.
> Add rule priority for allowing ServiceWorker initiated requests

- lib/utils.js
- test/utils.js
Expand the generateDNRRule helper function to support the tabIds/excludedTabIds, requestMethods/excludedRequestMethods and excludedResourceTypes conditions.
> Add generateDNRRule support for tabIds and requestMethods conditions

- test/utils.js
The generateDNRRule was originally only intended for use in the tds.js
module, but since it is now used elsewhere it should have proper test
coverage.
> Improve test coverage of generateDNRRule

- lib/gpc.js
- lib/rulePriorities.js
- lib/temporaryAllowlist.js
- test/rulePriorities.js
We recently realised[1] that some relative rule priorities weren't
correct. For example, the contentBlocking allowlist was not taking
priority over the tracker blocking allowlist. While discussing those
relative priorities, we agreed it would be nice to have a better
overview of them all too.
So let's adjust some of the rule priorities here, and also take care
to expand the rule priority tests to provide more of an overview.
1 - https://github.com/duckduckgo/ddg2dnr/pull/49#discussion_r1035658292
> Rethink some relative rule priorities and expand the tests

- lib/combined.js
- lib/cookies.js
- lib/extensionConfiguration.js
- lib/tds.js
- lib/utils.js
- test/cookies.js
- test/referenceTests.js
- test/rulePriorities.js
- test/utils.js
- Add method for generating dynamic modifyHeader rules, given a blocklist and 1st and 3rd party exception domains.
- Includes reference tests for cookie header blocking
> HTTP Cookie blocking

- README.md
- lib/ampProtection.js
- lib/extensionConfiguration.js
- test/ampProtection.js
- test/rulePriorities.js
The AMP link protection privacy feature redirects the user from AMP hosted pages[1] to the canonical source. It has two parts:
The AMP link protection privacy feature redirects the user from AMP
hosted pages[1] to the canonical source. It has two parts:
1. "Simple link redirection" - Redirect main_frame requests matching
AMP regular expressions to strip the AMP prefix from the URL.
2. "1st party hosted AMP extraction" - Request the AMP URL in the
background, extract the canonical URL from the DOM, redirect to the
canonical URL.
So far, we're just implementing simple link redirection here. Also,
note that we can only (for now) support regular expressions containing
one capturing group that ends at the end of the regular expression.
1 - https://developers.google.com/amp
> Add basic support for AMP link protection

- package-lock.json
- package.json
Let's remove the version number from package.json, Git tags are enough
anyway. This should clear the way to use the GitHub UI for future
releases.
> Remove version from package.json

- lib/tds.js
- lib/utils.js
- test/tds.js
- test/utils.js
For "Click to Load" tracker entry rules, we produce both the original
blocking/redirection declarativeNetRequest rule and the inverse
allowing declarativeNetRequest rule. Refactor the code used to
generate the inverse rules:
- Instead of hardcoding all of the custom 'block-ctl-*' tracker entry
rule actions, let's only hardcode the 'block-ctl-' prefix. That
way, the extension can decide which "Click to Load"
declarativeNetRequest rules should be disabled by default (by
enabling the inverse allowing rules by default). In turn, that
means the extension configuration can be used to specify which
"Click to Load" rules in the block list should be applied.
- Expand storeInLookup to support raw Object lookups and use that for
the generation of the "Click to Load" allowing rule lookup.
- Take care …
> Refactor "Click to Load" handling

- lib/tds.js
- test/tds.js
Click to Load allowing rules (like other allowing rules) don't need to
be limited to third-party matches. We already took care to remove
domainType conditions therefore, but we can also remove
excludedInitiatorDomains for when the allowed entity has multiple
associated domains.
> Simplify Click to Load allowing rules further

- lib/tds.js
- test/tds.js
Adding support for option rules. 
- [Reference tests](https://github.com/duckduckgo/privacy-reference-tests/pull/76) for option rules
- [Updated docs](https://github.com/duckduckgo/tracker-blocklists/pull/8) with example and implementation guidelines
Option rules act like a normal block rule in MV3, we just need to set the initiatorDomains and resourceTypes. 
Testing
- `npm run test` to run privacy reference tests. Make sure you have the options tests in the linked PR above
- Test Page
- Build the MV3 extension using this test blocklist https://staticcdn.duckduckgo.com/trackerblocking/beta/tds-options.json
- Go to http://privacy-test-pages.glitch.me/tracker-site-blocking/index.html and run the tests. You can also check the extension devtools to see that the correct rule is matching on …
> Support option rules
